import { useEffect, useState } from "react";
import { Api, waLink } from "../api";
import { Car, formatPrice } from "../types";

interface Props { car: Car | null; onClose: () => void; }

export default function LeadModal({ car, onClose }: Props) {
  const [nome, setNome] = useState(""); const [email, setEmail] = useState(""); const [telefone, setTelefone] = useState(""); const [mensagem, setMensagem] = useState(""); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [sent, setSent] = useState(false);
  useEffect(() => { setSent(false); setError(""); }, [car]);
  if (!car) return null;
  const submit = async (e: React.FormEvent) => { e.preventDefault(); setError(""); setLoading(true); try { const data = await Api.createLead({ nome, email, telefone, mensagem: mensagem || `Tenho interesse no ${car.marca} ${car.modelo} (${car.ano})`, carro_id: car.id }); setSent(true); const text = `Olá, ADARGA Soluções! Meu nome é ${nome}.\nTenho interesse no veículo: ${car.marca} ${car.modelo} ${car.ano} — ${formatPrice(car.preco)}.\nE-mail: ${email}\nTelefone: ${telefone}\n\n${mensagem || ""}`; window.open(waLink(data.whatsapp, text), "_blank"); } catch (err: any) { setError(err.response?.data?.error || "Não foi possível enviar. Tente novamente."); } finally { setLoading(false); } };
  return <div className="modal-backdrop" onClick={onClose}><div className="modal" onClick={(e) => e.stopPropagation()}>{!sent ? <><div className="modal-header"><h3>Interesse em {car.marca} {car.modelo}</h3><button className="modal-close" onClick={onClose} aria-label="Fechar">×</button></div><p className="form-sub" style={{ marginBottom: 18 }}>Preencha seus dados para receber nossa oferta e seguir o atendimento pelo WhatsApp.</p><form onSubmit={submit}><div className="form-group"><label>Nome completo *</label><input className="form-control" value={nome} onChange={(e) => setNome(e.target.value)} required placeholder="Seu nome" /></div><div className="form-group"><label>E-mail *</label><input className="form-control" type="email" value={email} onChange={(e) => setEmail(e.target.value)} required placeholder="voce@empresa.com.br" /></div><div className="form-group"><label>WhatsApp *</label><input className="form-control" type="tel" value={telefone} onChange={(e) => setTelefone(e.target.value)} required placeholder="(11) 99999-9999" /></div><div className="form-group"><label>Mensagem</label><textarea className="form-control" value={mensagem} onChange={(e) => setMensagem(e.target.value)} placeholder="Conte sobre sua necessidade (opcional)" /></div>{error && <p className="form-msg err">{error}</p>}<button className="btn btn-gold" style={{ width: "100%" }} disabled={loading}>{loading ? "Enviando..." : "Enviar e continuar no WhatsApp"}</button></form></> : <div style={{ textAlign: "center", padding: "20px 0" }}><div style={{ color: "var(--success)", fontSize: 44, marginBottom: 12 }}>✓</div><h3>Obrigado, {nome.split(" ")[0]}!</h3><p className="form-sub">Seus dados foram recebidos. O WhatsApp abrirá para concluirmos seu atendimento.</p><button className="btn btn-dark" style={{ marginTop: 18 }} onClick={onClose}>Fechar</button></div>}</div></div>;
}
